trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'To-ADO'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t bishalacr435.azurecr.io/web-game:tag 2048-game
      az acr login -n bishalacr435
      docker push bishalacr435.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'To-ADO'
    azureResourceGroup: 'MyResourceGroup'
    kubernetesCluster: 'my-aks-cluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'To-ADO'
    azureContainerRegistry: 'bishalacr435.azurecr.io'
    forceUpdate: false
